ps = ["PSP", "PS2", "PS3", "PS4"]
ps.append("PS5")
print(ps)
y = ps.count("PS2")
print(y)
xb = ["Xbox 360", "Xbox one", "Xbox one X"]
xb.extend(ps)
print(xb)
z = ps.index("PSP")
print(z)
ps.insert(3, "PS6")
print(ps)
ps.pop(4)
print(ps)
xb.remove("Xbox one X")
print(xb)
ps.reverse()
print(ps)
xb.sort()
print(xb)
ps.clear()
