txt = "Hello , Welcome to python!"
x = txt.capitalize()
print(x)
y = txt.casefold()
print(y)
l1 = 'Banana'
z = l1.center(15)
print(z)
l2 = ' I love USA, USA is my favourite place'
x = l2.count('USA')
print(x)
l3 = ' My name is Srijan '
y = l3.encode()
print(y)
z = txt.endswitch('l')
print(z)
l4 = ' H\te\tl\tl\to'
a = l4.expandtabs(5)
print(a)
x = txt.find('Hello')
print(x)
y = txt.index('Welcome')
print(y)
z = txt.isdigit()
print(z)
m = txt.isdecimal()
print(m)
n = txt.isidentifier()
print(n)
d = txt.islower()
print(d)
y = txt.split()
print(y)
z = l1.strip()
print("Of all fruits ", z, " is my favourite")
z = txt.upper()
print(z)
y = txt.title()
print(y)
m = l1.swapcase()
print(m)
z = l3.zfill(30)
print(z)
n = txt.startswith('and')
print(n)
