veges = ['Cabbage', 'Cauliflower', 'Onion', 'Potato', 'Ladyfinger']
veges.append('Bottlegourd')
print(veges)
y = veges.count('Onion')
print(y)
fruit = ['Orange', 'Apple', 'Mango', 'Banana']
fruit.extend(veges)
print(fruit)
z = veges.index('Cabbage')
print(z)
veges.insert(3, 'Tomato')
print(veges)
veges.pop(4)
print(veges)
fruit.remove('Banana')
print(fruit)
veges.reverse()
print(veges)
fruit.sort()
print(fruit)
veges.clear()
