d1 = {"C": "Easy", "C++": "Moderate", "Python": "Easy"}
print(d1)
x = d1.copy()
print(x)
y = d1.get("c++")
print(y)
z = d1.items()
print(z)
m = d1.keys()
print(m)
n = d1.pop("c++")
print(d1)
x = d1.popitem()
print(d1)
y = d1.setdefualt("python", "Super easy")
print(d1)
z = d1.update({"Java": "Tough"})
print(d1)
n = d1.values()
print(n)
x = ("Key 1", "Key 2")
y = 0
d1 = dict.fromkeys(x, y)
print(d1)
d1.clear()
print(d1)
